import React from 'react';
import { LegalReport, Risk, Clause } from '../types';
import { Icons } from './Icons';

interface AnalysisResultProps {
  report: LegalReport;
}

const AnalysisResult: React.FC<AnalysisResultProps> = ({ report }) => {
  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-green-600 bg-green-50 border-green-200';
    if (score >= 60) return 'text-yellow-600 bg-yellow-50 border-yellow-200';
    return 'text-red-600 bg-red-50 border-red-200';
  };

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Overview Card */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6">
            <div>
                <h3 className="text-2xl font-serif font-bold text-gray-900">{report.documentType || 'Document'} Analysis</h3>
                <p className="text-gray-500 mt-1">Generated by Veritas AI • Official Verification Pending</p>
            </div>
            <div className={`mt-4 md:mt-0 px-6 py-3 rounded-lg border flex flex-col items-center ${getScoreColor(report.overallScore)}`}>
                <span className="text-sm font-semibold uppercase tracking-wider">Safety Score</span>
                <span className="text-3xl font-bold">{report.overallScore}/100</span>
            </div>
        </div>
        
        <div className="prose prose-sm text-gray-600 max-w-none bg-gray-50 p-4 rounded-md border border-gray-100">
            <h4 className="text-gray-900 font-serif font-semibold mb-2">Executive Summary</h4>
            <p>{report.summary}</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Risks Section */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
            <div className="flex items-center mb-6 border-b border-gray-100 pb-4">
                <Icons.ShieldAlert className="h-6 w-6 text-crimson-600 mr-2" />
                <h3 className="text-xl font-serif font-bold text-gray-900">Identified Risks</h3>
            </div>
            <div className="space-y-4">
                {report.risks.map((risk, idx) => (
                    <div key={idx} className="border-l-4 border-crimson-600 bg-red-50 p-4 rounded-r-md">
                        <div className="flex justify-between items-center mb-2">
                             <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${risk.severity === 'High' ? 'bg-red-200 text-red-800' : 'bg-yellow-200 text-yellow-800'}`}>
                                {risk.severity.toUpperCase()} PRIORITY
                             </span>
                        </div>
                        <p className="text-gray-800 font-medium text-sm">{risk.description}</p>
                        <div className="mt-3 flex items-start text-sm text-gray-600">
                            <Icons.ArrowRight className="h-4 w-4 mr-2 mt-0.5 text-crimson-600 shrink-0" />
                            <span><span className="font-semibold">Action:</span> {risk.recommendation}</span>
                        </div>
                    </div>
                ))}
            </div>
        </div>

        {/* Key Clauses Section */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
            <div className="flex items-center mb-6 border-b border-gray-100 pb-4">
                <Icons.FileText className="h-6 w-6 text-blue-600 mr-2" />
                <h3 className="text-xl font-serif font-bold text-gray-900">Key Clauses</h3>
            </div>
            <div className="space-y-6">
                {report.keyClauses.map((clause, idx) => (
                    <div key={idx} className="relative pl-6 border-l border-gray-200">
                        <div className="absolute -left-1.5 top-1 h-3 w-3 rounded-full bg-blue-600"></div>
                        <h4 className="text-lg font-serif font-semibold text-gray-900">{clause.title}</h4>
                        <p className="text-sm text-gray-600 mt-1">{clause.summary}</p>
                        <p className="text-xs text-blue-700 font-medium mt-2 bg-blue-50 inline-block px-2 py-1 rounded">
                            Significance: {clause.significance}
                        </p>
                    </div>
                ))}
            </div>
        </div>
      </div>
      
      {/* Recommendations */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
           <h3 className="text-xl font-serif font-bold text-gray-900 mb-4">Strategic Recommendations</h3>
           <ul className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {report.recommendations.map((rec, idx) => (
                    <li key={idx} className="flex items-start">
                        <Icons.CheckCircle className="h-5 w-5 text-green-500 mr-3 mt-0.5 shrink-0" />
                        <span className="text-gray-700 text-sm">{rec}</span>
                    </li>
                ))}
           </ul>
      </div>
    </div>
  );
};

export default AnalysisResult;